# Generated by Django 6.0.3 on 2026-04-07 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduleSolver', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], max_length=3)),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('start_am_pm', models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], max_length=2)),
                ('end_am_pm', models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], max_length=2)),
                ('reason', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='form',
            name='year',
            field=models.CharField(choices=[('FN', 'Freshman'), ('SE', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior')], max_length=2, null=True),
        ),
    ]
