# Generated by Django 6.0.3 on 2026-04-08 23:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduleSolver', '0002_schedule_form_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='preferences',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2), blank=True, choices=[('WE', 'Weekend Shifts'), ('EM', 'Early Morning Shifts'), ('LN', 'Late Night Shifts')], default=list),
        ),
        migrations.AddField(
            model_name='form',
            name='sports',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
