# Generated by Django 6.0.3 on 2026-04-09 20:45

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduleSolver', '0004_alter_form_preferences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='preferences',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('WE', 'Weekend Shifts'), ('EM', 'Early Morning Shifts'), ('LN', 'Late Night Shifts')], max_length=2), blank=True, default=list),
        ),
    ]
