# Generated by Django 6.0.3 on 2026-04-29 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduleSolver', '0005_alter_form_preferences'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Form',
            new_name='Application',
        ),
    ]
